export const lng =
{
    fa: {
        translation: {
            "welcome": " خوش آمدید",
            "TEJARAT_BANK": "بانک تجارت",
            "MOBILE_BANK_TEJERAT": "همراه بانک تجارت",
            "USER_NAME": "نام کاربری - شماره ملی",
            "PASSWORD": "رمز ورود",
            "LOGIN": "ورود",
            "FORGOT_PASS": "ثبت نام / فراموشی رمز",
            "SHETAB_LOGIN_LINK": "کارت های شتابی",
            "WELLCOM_MESSAGE": "به همراه بانک تجارت خوش آمدید",
            "NATIONAL_CODE": "شناسه ملی",
            "REAL_NATIONAL_CODE": "کد ملی",
            "POS_STORE" : 'پایانه فروشگاهی',
            "POS" : 'پایانه',

            "PHONE_NUMBER": "شماره همراه",
            "SEND": "ارسال",
            "ACCOUNTS": "حساب ها",
            "CARDS": "کارت ها",
            "SERVIECES": "خدمات",
            "USER_ACCOUNT": "حساب کابری",
            "BALANCE": "موجودی",
            "MONEY_TRANSFER": "انتقال وجه",
            "MONEY_TRANSFER_MOBILE": "انتقال به موبایل",
            "SIM_CARD_CHARGE": "شارژ سیم کارت",
            "PAY_BILLS": "پرداخت قبوض",
            "TURNOVER": "گردش حساب",
            "INTERNET_PACKAGE": "بسته اینترنت",
            "CHARITY": "نیکوکاری",
            "ORGAN_PAYMENT": "پرداخت سازمانی",
            "DETAILS": "جزئیات",
            "DEST_ACCOUNT_NUMBER": "شماره حساب مقصد",
            "AMOUNT": "مبلغ",
            "TRANSFER_COMMENTS": "شرح انتقال",
            "SOURCE_COMMENT": "شرح مبدا",
            "TARGET_COMMENT": "شرح مقصد",
            "DEPOSIT_ID": "شناسه واریز",
            "TEJARAT": "تجارت",
            "MOBILE": "موبایل",
            "PAYA_SATNA": "پایا/ساتنا",
            "HELP": "راهنما",
            "ERROR": "خطا",
            "PAYMENT_RECEIPT":'رسید پرداختی',
            "USER_NAME_IS_EMPTY": "نام کاربری خود را وارد کنید",
            "PASSWORD_IS_EMPTY": "رمز عبور خود را وارد کنید",
            "ADD_ACCOUNT_DESC": "لطفا شماره همراه خود را جهت فعال سازی وارد کرده و گزینه ارسال رو انتخاب کنید.",
            "MOBILE_NUMBER": "شماره موبایل",
            "ADD_ACCOUNT": "افزودن حساب",
            "DEST_MOBILE_NUMBER": "شماره موبایل مقصد",
            "DEST_SHEBA_NUMBER": "شماره شبا مقصد",
            "LOG_NUMBER": "حساب",
            "FILTER": "فیلتر",
            "SEND_LOG": "ارسال صورتحساب",
            "CALCULATOR": "ماشین حساب",
            "VIEW": "نمایش",
            "LOG_NUMBER_LABLE": "تعداد صورت حساب",
            "FROM_DATE": "از تاریخ",
            "TO_DATE": "تا تاریخ",
            "SELECT_PLACEHOLDER": "انتخاب...",
            "EXIT": "خروج",
            "WILL_YOU_EXIT": "آیا مایل به خروج هستید؟",
            "YES": "بله",
            "NO": "خیر",
            "USERNAME_ID": "شناسه کاربری",
            "SETTINGS": "تنظیمات",
            "ABOUT_US": "درباره ما",
            "SEND_COMMENT": "ارسال نظر",
            "RIAL": "ریال",
            "IRR": "ریال",
            "ACCOUNT_NUMBER": "شماره حساب",
            "ACCOUNT_BALANCE": "موجودی قابل برداشت",
            "ACCOUNT_BALANCE_UPDATED": "موجودی حساب بروزرسانی شد.",
            "SELECT_SOURCE_ACCOUNT": "انتخاب حساب مبدأ",
            "SEARCH": "جستجو",
            "BLOCK_ACCOUNT": "مسدودی حساب",
            "BLOCK_ACCOUNT_INQUERY": "استعلام مسدودی حساب",
            "INSTANT_MESSAGE": "پیامک لحظه ای",
            "COPY_TO_CILPBOARD": "کپی در حافظه",
            "EDIT_ACCOUNT_TITLE": "ویرایش",
            "SOCIAL_SHARING": "اشتراک گذاری",
            "ACCOUNT_INFO": "اطلاعات حساب",
            "DONT_SHOW_ACCOUNT": "عدم نمایش",
            "DEFAULT_TRANSFER_MOBILE": "پیش فرض انتقال موبایلی",
            "SELECT": "انتخاب",
            "DEST_ACCOUNTS": "حساب های مقصد",
            "MYSELF_ACCOUNTS": "حساب های خودم",
            "ADD": " افزودن",
            "ACCOUNT": "حساب",
            "CARD": "کارت",
            "SHEBA": " شبا",
            "CARD_TITLE": "عنوان کارت",
            "CARD_NUMBER": "شماره کارت",
            "SAVE": "ذخیره",
            "ACCOUNT_TITLE": "عنوان حساب",
            "SHEBA_TITLE": "عنوان شبا",
            "SHEBA_NUMBER": "شماره شبا",
            "DEST_ACCOUNTS_MANAGEMENT": "مدیریت مقصدها",

            "CHEQUE_SAYADNUMBER_OBLIGATION": "تکمیل فیلد شناسه صیادی الزامی است",
            "CHEQUE_ACCOUNTNUMBER_OBLIGATION": "تکمیل فیلد شماره حساب الزامی است",

            "CHEQUE_NATIONALCODE_OBLIGATION": "تکمیل فیلد شناسه الزامی است",
            "CHEQUE_BENEFICIARY_OBLIGATION": "لیست گیرندگان و امضاکنندگان را تکمیل نمائید",


            "CHEQUE_MANAGEMENT": "مدیریت چک",
            "CHEQUE_INQUERY": "استعلام چک",
            "CHEQUE_SAYAD": "چک صیادی",
            "CHEQUE_SERVICES": " خدمات چک صیادی",
            "CHEQUE_DRAWER_OPERATION": "افزودن چک",
            "SAYAD_CHEQUE_INQUIRY": "استعلام چک صادر شده از سامانه صیاد",
            "SAYAD_INQUIRY": "استعلام چک صادر شده",
            "SAYAD_INQUIRY_INFORMATION": "استعلام مشخصات داخلی چک",
            "CHEQUE_RECIEVER_OPERATION": "استعلام وضعیت پروفایل مشتری در چکاد",
            "CHEKAD_THREE_MONTHS_ERROR": "نمایش اطلاعات تنها در بازه سه ماهه مقدور میباشد.",
            "ADD_NEW_CHEQUE": "افزودن چک جدید",
            "ADD_SAYAD_CHEQUE": "افزودن به چک های صادر شده",
            "SAYAD_NUMBER": "شناسه 16 رقمی صیاد",
            "DISPENSING": "انصراف",
            "SAYAD_SERIALNUMBER": "کد رهگیری",
            "SAYAD_SERINUMBER": "شناسه صیادی",
            "SAYAD_PAY": "مبلغ",
            "SAYAD_DATE": "تاریخ سر رسید",
            "CHECK_OPERATION": "عملیات چک صیادی",
            "SAVE_SAYAD_CHEQUE": "ثبت چک",
            "SAVE_SAYAD_CHEQUE_SUCCESSFULY": "چک صیادی با موفقیت ثبت شد.",
            "SERI_NUMBER": "سری عددی",
            "PAY_REASON_CODE": "بابت",
            "PAY_REASON_DESCRIB": "شرح بابت",
            "SELECT_PAY_REASON_DESCRIB": "انتخاب شرح بابت",
            "NEXT_STEP": "بعدی",
            "PREV_STEP": "قبلی",
            "MANAGER": "مدیریت کارت و حساب",
            "BENEFICIARIES": "گیرندگان",
            "BENEFICIARIES_INFO": "مشخصات گیرنده",
            "SAYAD_CHECK_REGISTER": "ثبت صدور چک",
            "SAYAD_SELECT_PERSON_TYPE": "انتخاب نوع شخص",


            "SAYAD_CHECKBOOK_REGISTER": "صدور دسته چک",
            "SAYAD_CHECKBOOK_SEND_METHOD": "نحوه ارسال",
            "SAYAD_CHECKBOOK_SELECT_SEND_METHOD": "انتخاب نحوه دریافت دسته چک",
            "SAYAD_CHECKBOOK_BRANCH_METHOD": "دریافت از شعبه",

            "SAYAD_CHECKBOOK_HOME_METHOD": "دریافت از درب منزل",




            "FILL_REASONCODE_OBLIGATORY": "تکمیل فیلد بابت الزامی است",
            "FILL_AMOUNT_OBLIGATORY": "تکمیل فیلد مبلغ چک الزامی است",
            "FILL_REASON_OBLIGATORY": "تکمیل فیلد شرح بابت الزامی است",
            "FILL_BENEFICIARIES_OBLIGATORY": "افزودن گیرنده الزامی است",

            "SELECT_DUEDATE": "تاریخ سررسید چک را انتخاب کنید",
            "ADD_NEW_PERSON": "افزودن شخص جدید",
            "ADD_PERSON": "افزودن شخص",
            "ADD_NEW_PERSON_TOLIST": "افزودن شخص جدید به لیست",
            "SIGNERS": "امضاکنندگان",
            "LEGAL_PERSON": "حقوقی",
            "REAL_PERSON": "حقیقی",
            "PERSON_KIND": "نوع شخص",
            "FOREIN_CODE": "شماره فراگیر اتباع",

            "SEND_OTP_TO_PICHAK": "ارسال به پیچک",
            "SEND_OTP_TO_SAYAD": "ارسال به سامانه صیاد",

            "SEND_PICHAK_OTP_MESSAGE": "برای تایید نهایی چک،باید درخواست شما به سامانه پیچک ارسال گردد. از طریق دکمه ارسال درخواست می توانید در این مرحله درخواست خود را به سامانه پیچک ارسال نمایید.",
            "SEND_REQUEST": "ارسال درخواست",
            "LATER": "بعدا",
            "PHONENUMBER_CHEQUE_CONFIRM": "شماره همراه خود را برای تایید دریافت و مندرجات چک انتخاب کنید",
            "SAYAD_CONFIRM_MOBILE_NUMBER_MSG": "لطفا رمز پیامک شده را برای تایید شماره همراه خود وارد نمایید .",
            "CONFIRM_REQUEST": "ثبت درخواست",
            "SAYAD_CHECK_INQUIRY": "استعلام چک دریافتی",
            "SAYAD_ACCOUNT_NUMBER": "شماره حساب",
            "SELECT_ACCOUNT_NUMBER": "انتخاب شماره حساب",
            "SAYAD_INFORMATION": "اطلاعات چک",
            "CONFIRM_REJECT_CHEQUE": "تایید دریافت / لغو دریافت چک",
            "SAYAD_TRANSFER_TO_BENEFICIANERY": "انتقال به گیرنده جدید",
            "SAYAD_REJECT_CHEQUE": "عودت چک",
            "SAYAD_TRANSFER_CHEQUE": "انتقال چک",
            "SAYAD_TRANSFER": "انتقال",
            "SAYAD_REJECT_DESCRIPTION": "شرح عودت",
            "SAYAD_REJECT_DESCRIPTION_FORCE": "تکمیل شرح اجباری است.",
            "SAYAD_REJECT_REASON_FORCE": "تکمیل بابت اجباری است.",
            "SAYAD_SAYADNUMBER_FORCE": "تکمیل شناسه صیاد اجباری است.",
            "SAYAD_OPERATION_HISTORY": "سوابق عملیات چک",
            "SAYAD_CHECKBOOK_REQUEST": "درخواست غیرحضوری دسته چک",
            "SAYAD_ISSUED_INQUIRY": "استعلام چک صادر شده از سامانه صیاد",
            "SAYAD_CHECKBOOK_INQUIRY": "استعلام برگه های دسته چک",



            "RECIEVED_CHEQUE_CONFIRM": "تایید دریافت و مندرجات چک",
            "ACCEPT_CHEQUE": "پذیرش چک",
            "REJECT_CHEQUE": "رد چک",
            "REJECT_CHEQUE_REASON": "انتخاب دلیل رد چک",
            "REJECT_CHEQUE_REASON_OBLIGATION": "لطفا دلیل رد چک را انتخاب کنید",

            "FAILURE_RECIEVE_CHEQUE": "عدم دریافت فیزیک چک",
            "CONTRADICTION_INFORMATION_ITEMS": "مغایرت اقلام اطلاعاتی فیزیک با مندرجات در سامانه",
            "FAILURE_TRANSACTION": "عدم انجام معامله",
            "SAYAD_DELETE_CONFIRM": "آیا مایل به حذف این چک هستید؟",
            "SAYAD_SERIAL_NUMBER": "شماره سریال چک",
            "SAYAD_CONFIRM_TRANSFER": "آیا از انتقال چک به این اشخاص اطمینان دارید؟",
            "SAYAD_CONFIRM_GIVEBACK": "آیا از عودت این چک اطمینان دارید؟",
            "SAYAD_COMMON_INQUIRY": "استعلام عمومی چک",
            "SAYAD_TRANSFER_QUEU": "استعلام زنجیره انتقال چک",
            "SAYAD_TRANSFER_QUEU_INFO": "اطلاعات استعلام زنجیره انتقال چک",

            "SAYAD_NO_CHOICE": "گزینه ای برای انتخاب وجود ندارد",
            "SAYAD_CHEQUE_CONFIRMED": "چک با موفقیت تایید شد",
            "SAYAD_CHEQUE_REJECT": "چک با موفقیت رد شد",
            "SAYAD_CHEQUE_GIVEBACK": "چک با موفقیت عودت شد",

            "SAYAD_REMINDER": "تنظیم یادآور",
            "SAYAD_TRANSFARRED_STATUS": "وضعیت چک واگذار شده به حساب",


            "IN_PROGRESS": "در حال انجام",



            "PAPER_CHEQUE": "چک کاغذی",
            "ELECTRONIC_CHEQUE": "چک دیجیتال",
            "CHEKAD_CLIENT_PROFILE": "پروفایل مشتری در چکاد",
            "CHECKAD_ACTIVATE_UPDATE": "فعالسازی / بروزرسانی در سامانه چکاد",
            "SELECT_TOKEN_TYPE": "انتخاب نوع توکن",
            "CHEKAD_ACTIVATE": "فعالسازی در سامانه چکاد",
            "CHEKAD_COMPELETE_OTP_FIELD": "لطفا رمز پیامک شده را وارد کنید",
            "CHEKAD_DEACTIVE": "غیرفعالسازی در سامانه چکاد",
            "CHEKAD_ELECTRONIC_OPERATIONS": "عملیات چک دیجیتال",
            "CHEKAD_CHECKBOOK_REQUEST": "درخواست دسته چک",
            "CHEKAD_ISSUING_CHECK": "صدور چک",
            "CHEKAD_ISSUE_DATE": "تاریخ ثبت چک",
            "CHEKAD_CARTABLE_OF_INCOMING_CHECKS": "کارتابل چک های دریافتی",
            "CHEKAD_BLOCK_AND_UNBLOCK": "مسدودی / رفع مسدودی چک",
            "CHEKAD_CANCELLATION": "ابطال چک",
            "CHEKAD_GUARANTEE_OPERATIONS": "عملیات ضمانت چک",
            "CHEKAD_OTHER_SEVICES": "سایر خدمات چک",
            "CHEKAD_REGISTERED_HISTORY": "سوابق چک های ثبت شده",
            "CHEKAD_DETAILS_INQUIRY": "استعلام مشخصات چک دیجیتال",
            "CHEKAD_GUARANTEE_STATUS_INQUIRY": "استعلام وضعیت ضمانت چک",
            "CHEKAD_FILL_INPUTS": "تکمیل تمامی فیلدها اجباری است",
            "CHEKAD_SERI": "سری چک",
            "CHEKAD_GUARANTEE_STATUS": "وضعیت ضمانت",
            "CHEKAD_GUARANTORS_NAME": "اسامی ضامنین",
            "CHEKAD_CANCELLATION_WITH_SAYADNUMBER": "آیا از ابطال چک با شناسه صیاد ",
            "CHEKAD_SURE_REQUEST": " اطمینان دارید؟",
            "CHEKAD_BLOCK_STATUS": "وضعیت مسدودی چک",
            "CHEKAD_TRANSFER_GIVEBACK": "انتقال / عودت",
            "CHEKAD_REJECT": "عودت",
            "CHEKAD_GIVEBACK_CONFIRM": "آیا عودت چک با شماره صیاد  ",
            "CHEKAD_SURE_GIVEBACK": " مورد تایید است؟",
            "CHEKAD_ISSUED": "چک های صادر شده",
            "CHEKAD": "چکاد",
            "CHEKAD_SAYAD_NUBER": "شماره صیاد",
            "ADD_NEW_BENEFICIARY": "افزودن گیرنده جدید",
            "ADD_NEW_SIGNER": "افزودن امضاکننده جدید",
            "ADD_NEW_GUARANTOR": "افزودن ضامن جدید",
            "CHEKAD_SENT_TO_CENTER": "ارسال درخواست سامانه چکاد",
            "CHEKAD_SENT_TO_CENTER_TEXT": "برای تایید نهایی چک، باید درخواست شما به سامانه چکاد ارسال گردد. از طریق دکمه ارسال درخواست می توانید در این مرحله درخواست خود را به سامانه چکاد ارسال نمایید.",
            "CHEKAD_ADD_BENEFICIARY_FORCED": "لطفا گیرندگان را وارد نمایید.",
            "CHEKAD_EDIT_SUCCESS": "ویرایش با موفقیت انجام شد",
            "CHEKAD_TRANSFER_CONFIRM": "آیا انتقال چک با شناسه صیاد  ",
            "CHEKAD_TRANSFER_CONFIRM_Q": "مورد تایید است؟>",
            "CHEKAD_LAST_UPDATE": "آخرین بروزرسانی",
            "CHEKAD_ASSIGN_UPDATE": " به منظور بروزرسانی کارتابل، ابتدا از طریق اپلیکیشن هامون اقدام به ثبت امضای دیجیتال نمایید.",
            "CHEKAD_PASS_CHECK": "نقد کردن چک",
            "CHEKAD_FINAL_STATUS": "ثبت نهایی",
            "CHEKAD_BANK_NAME": "بانک عامل",
            "CHEKAD_BLOCK_HAMON": " به منظور مسدودی و رفع مسدودی، ابتدا از طریق اپلیکیشن هامون اقدام به ثبت امضای دیجیتال نمایید.",
            "CHEKAD_DELIVER_DATE": "تاریخ تحویل",
            "CHEKAD_SERIAL_FROM": "سریال چک از",
            "CHEKAD_SERIAL_TO": "سریال چک تا",
            "CHEKAD_CHECK_KIND": "نوع چک",
            "CHEKAD_CHECKBOOK": "دسته چک",
            "CHEKAD_GUARANTEE_REQUEST_NOTE": "در صورتی که چک انتقال پیدا کرده و یا نقد شده باشد امکان ارایه این سرویس وجود ندارد",




            "CHEKAD_DETAILS_INQUIRY_OF_GUARANTOR": "استعلام اطلاعات چک توسط ضامن",
            "CHEKAD_DETERMIND_GUARANTOR": "تعیین ضامن توسط صادرکننده چک",
            "CHEKAD_REQUEST_STOP_GUARANTEE": "درخواست / توقف ضمانت چک",
            "CHEKAD_REQUEST_STOP_GUARANTEE_BY_RECIEVER": "درخواست / توقف ضمانت چک از سمت زینفع",
            "CHEKAD_REQUEST_GUARANTEE": "درخواست ضمانت",
            "CHEKAD_STOP_GUARANTEE": "توقف ضمانت",
            "CHEKAD_STOP_GUARANTEE_REQUEST": "درخواست توقف ضمانت چک",
            "CHEKAD_GUARANTEE": "ضمانت چک",
            "CHEKAD_GUARANTEE_ACCEPT": "قبول ضمانت",
            " b  n": "رد ضمانت",



            "CHEKAD_ADD_NEW_REQUEST": "افزودن درخواست جدید",
            "CHEKAD_ADD_ELECTRONIC_REQUEST": "افزودن درخواست دسته چک دیجیتال",
            "CHEKAD_ADD_PAPER_REQUEST": "افزودن درخواست دسته چک ",

            "CHEKAD_RULES": "قوانین چک",
            "NUMBER_OF_CHECKBOOKS": "تعداد کل دسته چکها",

            "NUMBER_OF_CHECKBOOK_SHEETS": "تعداد برگه دسته چک",
            "CHEKAD_SEND_REQUEST": "ارسال درخواست به شعبه",
            "CHEKAD_RECEIPT": "رسید دسته چک",
            "CHEKAD_TRANSFER": "انتقال",
            "CHEKAD_CHECKBOOK_PAGE": "برگه چک",

            "CHEKAD_TRANSACTION": "تراکنش چک صیادی",
            "CHEKAD_REGISTERED_DATE": "تاریخ ثبت چک",
            "CHEKAD_BLOCK_UNBLOCK": "مسدودی / رفع مسدودی",
            "CHEKAD_BLOCK": "مسدودی",
            "CHEKAD_UNBLOCK": "رفع مسدودی",
            "CHEKAD_SHEBA_NUMBER": "شماره شبا",
            "CHEKAD_STATUS": "وضعیت چک",
            "CHEKAD_DESCRIPTION": "شرح چک",
            "CHEKAD_ADD_PERSON_LIST": "افزودن شخص جدید به لیست",
            "MORE_DETAILS": "جزئیات بیشتر",
            "LESS_DETAILS": "جزئیات کمتر",
            "SENDER": "صادرکننده",
            "BENEFICIARY": "ذینفع",
            "TRANSFEREE": "انتقال گیرنده",
            "CHEKAD_SENDER": "صادرکنندگان",
            "CHEKAD_TRANSFEREE": "انتقال گیرنده",


            "INSTALLMENT_MANAGEMENT": "مدیریت اقساط",
            "BILL_MANAGEMENT": "مدیریت قبض ها",
            "BILL_LIST": "لیست قبض ها",
            "BILLA_ADD": "افزودن قبض جدید",
            "CREATE_NEW_BILL": "افزودن قبض جدید به لیست قبض ها",
            "BILL_EDIT": "ویرایش قبض",

            "BILL_EDIT_SUCCESS": "قبض با موفقیت ویرایش شد",
            "BILL_DELETE_SUCCESS": "قبض با موفقیت حذف شد",
            "SELECT_BILL_TYPE": "نوع قبض را مشخص کنید",


            "SHARE_CARD": "اشتراک کارت",
            "TRANSACTIONS_HISTORY": "سوابق تراکنش ",
            "BRANCHES_ARROUND": "شعب اطراف من",
            "CONVERTS": "تبدیل ها",
            "ENTER_COMPLETE_CONVERSION_INFORMATION": "اطلاعات تبدیل را کامل وارد نمایید",
            "CONVERT": "تبدیل",
            "DYNAMIC_PASS_SERVICES": "خدمات رمز پویا",
            "ADD_CARD": "افزودن کارت",
            "CVV2": "CVV2",
            "EXPIRE_DATE": "تاریخ انقضا",
            "MONTH": "ماه",
            "YEAR": "سال",
            "CARD_BALANCE": "موجودی قابل برداشت",
            "UPDATE": "بروزرسانی",
            "DEPOSIT": "واریز",
            "WITHDRAW": "برداشت",
            "ENTER_PRICE": "لطفا مبلغ را وارد کنید",
            "ENTER_DEST_ACCOUNT_NUMBER_NOTI": "لطفا شماره حساب مقصد را وارد نمایید",
            "ENTER_DEST_IBAN_NUMBER_NOTI": "لطفا شماره شبا مقصد را وارد نمایید",
            "ENTER_AMOUNT": "لطفا مبلغ را وارد نمایید",
            "DYNAMIC_PASSWORD": "رمز دوم یا پویا",
            "ENTER_DYNAMIC_PASSWORD": "لطفا رمز دوم کارت خود را وارد نمایید",
            "GET_BALANCE": "دریافت موجودی",
            "HAMRAZ": "همراز",
            "HARIM": "پیامکی",
            "CARD_DYNAMIC_PASS": "رمز پویا کارتی",
            "ACCOUNT_DYNAMIC_PASS": "رمز پویا حسابی",
            "DYNAMIC_PASS": "رمز پویا",
            "HAMRAZ_MENU": "همراز (رمز پویا تجارت)",
            "HARIM_MENU": "هریم (رمز پویا پیامکی)",
            "ENTER_PASS_CORRECTLY": " لطفا رمز خود را صحیح وارد نمایید",
            "YOUR_REQUEST_SENT_SUCCESSFULLY": "درخواست شما با موفقیت ارسال شد",
            "ACCOUNT_INFO_SAVED": "اطلاعات حساب ذخیره شد",
            "IBAN_INFO_SAVED": "اطلاعات شماره شبا ذخیره شد",
            "CARD_INFO_SAVED": "اطلاعات کارت ذخیره شد",
            "SECURITY": "امنیت",
            "CHANGE_PASSWORD": "تغییر رمز ورود به برنامه",
            "MOBILE_BANK_CHANGE_PASSWORD": "تغییر رمز همراه بانک",
            "CURRENT_PASSWORD": "رمز فعلی",
            "NEW_PASSWORD": "رمز جدید",
            "REPEAT_NEW_PASSWORD": "تکرار رمز جدید",
            "SAVE_CHANGE_PASSWORD": "ثبت",
            "CONFIRM_PASS_MISMATCH": "عدم تطابق رمز",
            "ENTER_CURRENT_PASS": "رمز فعلی رو کامل وارد کنید",
            "PASSWORD_CHANGED_SUCCESSFULLY": "تغییر رمز با موفقیت انجام شد.",
            "NEW_PASS_LENGTH_ERROR": "رمز انتخابی باید 6 تا 12 رقم باشد",
            "TRANSACTION_DETAIL": "جزئیات تراکنش",
            "DOCUMENT_DESC": "شرح سند",
            "DATE_TIME": "تاریخ و زمان",
            "DOCUMENT_NUMBER": "شماره سند",
            "TEJARAT_AD_MESSAGE": "عملیات بانکی خود را به همراه بانک تجارت بسپارید، حتی اگه در بانک ما حساب ندارید.",
            "SHARE_RECEIPE_IMAGE": "اشتراک عکس رسید",
            "SHARE_RECEIPE_CONTENT": "اشتراک متن رسید",
            "EMAIL": "ایمیل",
            "TO": "تا",
            "TRANSACTIONS_SENT_SUCCESSFULLY": "صورتحساب به ایمیل شما ارسال شد",
            "BLOCK_ACCOUNT_CARD": "مسدودی کارت و خدمات نوین",
            "BLOCK_ACCOUNT_SERVICES": "مسدودی خدمات نوین (همراه بانک، اینترنت بانک، تلفن بانک)",
            "ENTER_PASSWORD_TO_BLOCK_ACCOUNT": "لطفا رمز همراه بانک خود را برای مسدودسازی حساب وارد نمایید.",
            "ACCOUNT_BLOCKED_SUCCESSFULLY": "حساب شما با موفقیت مسدود شد",
            "MOBILE_BANK_PASS": "رمز همراه بانک",
            "ACCOUNT_MOBILE_BANK_PASS": "رمز یکبار مصرف حساب",
            "ACCOUNT_NUMBER_COPIED_TO_CLIPBOARD": "شماره حساب در حافظه موقت ذخیره شد.",
            "SHEBA_NUMBER_COPIED_TO_CLIPBOARD": "شماره شبا در حافظه موقت ذخیره شد",
            "CARD_NUMBER_COPIED_TO_CLIPBOARD": "شماره کارت در حافظه موقت ذخیره شد",
            "SAVE_ACCOUNT": "ثبت",
            "ACCOUNT_IS_ACTIVE": "حساب مورد نظر فعال می باشد",
            "ACCOUNT_IS_INACTIVE": "حساب موردنظر غیرفعال می باشد",
            "CARD_BALANCE_UPDATED": "موجوی کارت بروزرسانی شد.",
            "CARD_BALANCE_ENABLE_TEJARAT": "سرویس مورد نظر تنها در کارت بانک تجارت فعال می باشد.",
            "ENTER_CARD_TITLE": "عنوان کارت را وارد نمایید",
            "ENTER_VALID_CARD_NUMBER": "شماره کارت معتبر وارد نمایید",
            "CORRECT_CVV2_CODE": "رقم cvv2 را صحیح نمایید",
            "ENTER_VALID_DATE": "تاریخ انقضا معتبر وارد نمایید",
            "CONFIRM_TRANSFER": "تایید انتقال وجه",
            // "CONFIRM_TRANSFER": "تایید انتقال وجه",
            "TRANSACTION_TYPE": "نوع تراکنش",
            "SOURCE": "مبدأ",
            "DESTINATION": "مقصد",
            "ACCOUNT_OWNER_NAME": "نام صاحب حساب",
            "IBAM_OWNER_NAME": "نام صاحب شبا",
            "ENTER_MOBILE_BANK_PASSWORD": "لطفا رمز همراه بانک خود را وارد نمایید.",
            "TEJARAT_TRANSFER_ACCOUNT_TO_ACCOUNT": "انتقال وجه تجارت (حساب به حساب)",
            "TEJARAT_TRANSFER_CARD_TO_CARD": "انتقال وجه تجارت (کارت به کارت)",
            "SOURCE_ACCOUNT": "حساب مبدأ",
            "DEST_ACCOUNT": "حساب مقصد",
            "DATE_AND_TIME": "تاریخ و زمان",
            "TRACKING_CODE": "شماره پیگیری",
            "REFRENCE_NUMBER": "شماره مرجع",
            "STATUS_INQUERY": "استعلام وضعیت",
            "TRANSFRED_SUCCESSFULLY": "انتقال با موفقیت انجام شده است",
            "BILL_GENERAL": "خدماتی",
            "HAMRAH_AVAL": "همراه اول",
            "TWO_ID_BILL": "دو شناسه ای",
            "BILL_IDENTIFIRE": "شناسه قبض",
            "PAYMENT_IDENTIFIRE": "شناسه پرداخت",
            "BARCODE_READER": "بارکدخوان",
            "MYSELFE": "خودم",
            "INQUERY": "استعلام",
            "INQUIRY": "استعلام",
            "CONTINUE": "ادامه",
            "BUY_CHARGE": "خرید شارژ",
            "DIRECT_CHARGE": "شارژ مستقیم",
            "MOBILE_OPERATOR": "اپراتور",
            "CHARGE_TYPE": "نوع شارژ",
            "CAHRGE_AMOUNT": "مبلغ شارژ",
            "PIN_CAHRGE": "رمز شارژ",
            "AUTO_CHARGE": "شارژ خودکار",
            "COMMANDS": "دستورها",
            "ADD_NEW_COMMAND": "افزودن دستور جدید",
            "SELECT_OPERATOR": "انتخاب اپراتور",
            "IRAN_CELL": "ایرانسل",
            "RIGH_TELL": "رایتل",
            "CHARGE_TYPE_0": "عادی",
            "CHARGE_TYPE_1": "شگفت انگیز",
            "CHARGE_TYPE_2": "شورانگیز",
            // "IN_PROGRESS": "در حال انجام",

            "LINK_MOBILE_BANK": "*لینک دریافت همراه بانک*",
            "ENTER_DEST_CARD_NUMBER_NOTI": "لطفا شماره کارت مقصد را وارد نمایید",
            "DEST_CARD_NUMBER": "شماره کارت مقصد",
            "DEST_CARDS": "کارت های مقصد",
            "MYSELF_CARDS": "کارت های خودم",
            "INTERNET_MOBILE": "همراه",
            "INTERNET_TD_LTE": "TD-LTE",
            "INTERNET_TAX_AMOUNT": "مبلغ بسته به همراه مالیات",
            "PACKAGE": "بسته",
            "INSTITUTE": "موسسه",
            "ORGAN": "سازمان",
            "BLOCK_CARD": "مسدودی کارت",
            "DELETE": "حذف",
            "EDIT_CARD": "ویرایش",
            "ORGANS": "سازمانها",
            "BANK": "بانک",
            "BANK_TITLE": "نام بانک",
            "ENTER_CVV2_CODE": "رمز CVV2 را صحبح وارد نمایید.",
            "ENTER_EXPIRE_DATE": "لطفا تاریخ انقضا را صحیح وارد نمایید",
            "SOURCE_CARD": "کارت مبدأ",
            "DEST_CARD": "کارت مقصد",
            "CARD_OWNER_NAME": "نام صاحب کارت",
            "SAVE_CARD": "ثبت",
            "DEST_IBAN": "شبا مقصد",
            "STATUS": "وضعیت",
            "TITLE": "عنوان",
            "ACTIVE": "فعال",
            "INACTIVE": "غیرفعال",
            "DOING": "در حال انجام",
            "SELECT_CHARGE_TYPE": "انتخاب نوع شارژ",
            "SELECT_CHARGE_AMOUNT": "مبلغ شارژ",
            "NO_CHARGE_AVAILABLE_FOR_SELECTED_OPERATOR": "برای اپراتور انتخابی شارژی موجود نیست",
            "ENTER_TOPUP_PACKAGE": "بسته مورد نظر رو انتخاب کنید",
            "ENTER_TOPUP_MOBILE": "لطفا شماره همراه را وارد کنید",
            "ENTER_TOPUP_OPERATOR": "لطفا اپراتور مورد نظر را انتخاب کنید",
            "DIRECT": "مستقیم",
            "OPERATOR_TRACENUMBER": "کد پیگری اپراتور",
            "PUR_CHARGE": "خرید شارژ",
            "CONFIRM_PUR_CHARGE": "تایید خرید شارژ",
            "CLICK_CHARGE_CODE_TO_CALL": "باکلیک کد دستوری زیر را شماره گیری نمایید",
            "CHARGE_CODE_COPIED_TO_CLIPBOARD": "کد شارژ در حافظه موقت ذخیره شد",
            "CONFIRM_CHARITY_TRANSFER": "تایید کمک به نیکوکاری",
            "CHARITY_ORG_NAME": "نام موسسه",
            "CHARITY_ORG_ACCOUNT_NUMBER": "شماره حساب موسسه",
            "CHARITY_ORG_CARD_NUMBER": "شماره کارت موسسه",
            "PAYA_TRANSFER_MESSAGE": "شما در حال انتقال وجه پایا هستید.( انتقال در مقاطع زمانی مشخصی انجام می گردد)",
            "SATNA_TRANSFER_MESSAGE": "شما در حال انتقال وجه ساتنا هستید. ( انتقال با اندکی تاخیر در ساعات اداری)",
            "ORGAN_OWNER_ACCOUNT": "سازمان دارنده حساب",
            "CONFIRM_PAY_BILL": "تایید پرداخت قبض",
            "OPERATIONS": "عملیات",
            "PAY_BILL_ACCOUNT": "پرداخت قبض( حساب )",
            "PAY_BILL_CARD": "پرداخت قبض (کارت)",
            "PREPAID_SIM": "سیم کارت اعتباری",
            "POSTPAID_SIM": "سیم کارت دایمی",
            "ENTER_INTERNET_PACKAGE": "بسته موردنظر را انتخاب کنید",
            "CONFIRM_INTERNET_PACK": "تایید خرید بسته اینترنت",
            "PUR_INTERNET_PACK": "خرید بسته اینترنت",
            "INTERNET_PACK_TYPE": "نوع بسته",
            "CONFIRM_ORGAN_TRANSFER": "تایید پرداخت سازمانی",
            "INSTANT_MESSAGE_STATUS": "وضعیت های سرویس پیامک لحظه ای",
            "INACTIVE_INSTANT_MESSAGE_EXP": "غیرفعال: هیچ پیامک واریز و برداشتی رو حساب ارسال نمی گردد.",
            "ACTIVE_INSTANT_MESSAGE_EXP": "فعال: دریافت تمام پیامک های وایز و برداشت. ( این سرویس شامل کسر کارمزد می باشد )",
            "DEACTIVE_ACTIVE_INSTANT_MESSAGE_EXP": "غیر فعال",
            "IM_ACTIVATION_EXP": "فعال سازی پیامک برداشت و واریز (توجه: این سرویس شامل کارمزد به مبلغ 100,000 ربال است)",
            "HIDE_ACCOUNT_CONFIRM_MSG": "آیا از عدم نمایش حساب انتخاب شده اطممینان دارید؟",
            "HIDE_CARD_CONFIRM_MSG": "آیا از عدم نمایش کارت انتخاب شده اطممینان دارید؟",
            "DELETE_CARD_CONFIRM_MSG": "آیا مایل به حذف کارت مورد نظر هستید",
            "DELETE_REPORT_MSG": "آیا از حذف سابقه تراکنش اطمینان دارید؟",
            "DESTINATION_PHONE_NUMBER": "شماره همراه مخاطب",
            "CARD_CONFIRMATION_TOP_MSG": " برای مشاهده نام دارنده کارت مقصد، مشخصات کارت خود را وارد نمایید و کلید استعلام را بزنید.",
            "SHOW_CARD_OR_ACCOUNT": "نمایش کارت و حساب",


            "CELL_PHONE_TITLE": "تلفن",
            "UNKNOWN_TITLE": "",


            "GAS_TITLE": "گاز",
            "GAS": "گاز",
            "WATER_TITLE": "آب",
            "WATER": "آب",
            "ELECTRICITY": "برق",
            "ELECTRICITY_TITLE": "برق",
            "MOBILE_TITLE": "تلفن همراه - پایان دوره",
            "MOBILE_NOW_TITLE": "تلفن همراه - میاندوره",
            "TEL_TITLE": " تلفن ثابت - پایان دوره",
            "MOBILE_NOW": "تلفن همراه - میاندوره",
            "TEL_NOW": "تلفن ثابت - میان دوره",
            "TEL_NOW_TITLE": " تلفن ثابت - میان دوره",
            "TEL": "تلفن ثابت - میان دوره",
            "SUBSCRIPTION_NUMBER": "شماره اشتراک",
            "TEL_WITH_PRECODE": "شماره تلفن به همراه کد شهرستان",
            "GROUP": "گروه",
            "DESCRIPTION": "توضیحات",
            "CUSTOMER_BILL": "مشترک",
            "USE_TYPE": "نوع مصرف",
            "SUBSCRIPE_NUMBER": "شماره اشتراک",
            "FILE_NUMBER": "شماره پرونده",
            "UNIT_COUNT": "تعداد واحد",
            "METER_SERIAL": "سریال کنتور",
            "CAPACITY": "ظرفیت",
            "CURRENT_READING_DATE": "تاریخ قرائت فعلی",
            "PREVIOUS_READING_DATE": "تاریخ قرائت پیشین",
            "CURRENT_CAONTER_DIGIT": "رقم شمارشگر فعلی",
            "PREVIOUS_COUNTER_DIGIT": "رقم شمارشگر پیشین",
            "STANDARD_CONSUMPTION": "مصرف استاندارد",
            "BILL_TAXES": "عوارض",
            "INSURANCE": "بیمه",
            "COUNTER_ACTIVITY": "",
            "SERIAL_NUMBER": "سری",
            "OTHETR_DEBT": "بدیهی متفرقه",
            "REMAINING_DEBT": "مانده بدهی/ بستانکاری",
            "REMAINING_PREVIOUS_INVOICE": "مانده صورتحساب قبلی",
            "REMAINING_AMOUNT_1000": "مانده مبلغ هزار ریال",
            "DEDUCTION_AMOUNT_1000": "کسر مبلغ هزار ریال",
            "VILLAGE_GAZ_TAXES": "عوارض گازرسانی به روستا",
            "ADDRESS_CODE": "کد آدرس",
            "SHOW_DETAILS": "نمایش جزئیات",
            "HIDE_DETAILS": "عدم نمایش جزئیات",
            "TRANSFER_TEJARAT": "انتقال وجه (تجارت)",
            "TRANSFER_IBAN": "انتقال وجه پایا/ساتنا",
            "TRANSFER_CARD": "انتقال وجه (کارت)",
            "FARSI": "فارسی",
            "FINGLISH": "فینگلیش",
            "BILL": "قبض",
            "CHARGE": "شارژ",
            "INTERNET_PACKAGES": "بسته های اینترنت",
            "TRANSFER_FROM": "انتقال از",
            "TRANSFER_TO": "به",
            "FUND_TRANSFER_ACH": "انتقال وجه بین بانکی",
            "PAYMENT_FROM": "پرداخت از",
            "PAYA": "پایا",
            "SATNA": "ساتنا",
            "ALL": "همه",
            "OK": "تایید",
            "CANCEL": "لغو",

            "NULL": "لغو",
            "SUCCESS": "موفق",
            "FAIL": "ناموفق",
            "BILL_TYPE": "نوع قبض",
            "BILL_TITLE": "عنوان قبض",
            "HELP_TO": "کمک به",
            "pasargad": "پاسارگارد",
            "tejarat": "تجارت",
            "ayandeh": "آینده",
            "saman": "سامان",
            "mellat": "ملت",
            "maskan": "مسکن",
            "TRY_AGAIN": "تلاش مجدد",
            "CHARITY_MIN_AMOUNT": "حداقل مبلغ نیکوکاری 1000 ریال می باشد",
            "RESTCALL_TIMEOUT_MSG": "خطا در دسترسی به برنامه، مجددا تلاش کنید",
            "Internal Server Error": "خطا در دسترسی به برنامه، مجددا تلاش کنید",
            "TIMEOUT_MSG": "خطا در دسترسی به برنامه",
            "CONVERSIONS": "تبدیل ها",
            "ENTER_INFO_AND_SOURCE_TYPE": "اطلاعات و نوع شماره مبدا را وارد نمایید",
            "SELECT_BANK": "انتخاب بانک",
            "PAHSE_COUNT": "تعداد فاز",
            "ELECTRICY_CONSUME_AMOUNT": "بهای برق مصرفی",
            "ELC_COMPANY_NAME": "نام شرکت توزیع",
            "CUSTOMER_BILL_TYPE": "نوع مشترک",
            "POSTAL_CODE": "کد پستی",
            "ELC_IDENTIFIER_NUMBER": "شماره بدنه کنتور",
            "TARIFF_TYPE": "نوع تعرفه",
            "ELC_AMPER": "آمپراژ",
            "ELC_VOLTAGE": "نوع ولتاژ",
            "CUNSUMPTION_DEBT_AMOUNT": "مقدار بدهی مصرف",
            "OTHER_SERVICE_DEBT_AMOUNT": "بدهی سایر خدمات/خسارت",
            "BRANCHES_DEBT": "بدهی واگذاری انشعاب برای انشعابات قسط",
            "ADDRESS": "آدرس",
            "ACCOUNT_NUMBER_TEMPLATE": "شماره حساب قالب:",
            "SELECT_CONVERT_DEST_TYPE": "نوع تبدیل مقصد را انتخاب نمایید",
            "CONFIRM_DELETE_BILL": "آیا مایل به حذف قبض",
            "CONFIRM_DELETE_BILL_VERB": "هستید؟",

            "CARD_LESS_SERVICES": "خدمات بدون کارت",
            "LIST_OF_REQUESTS": "لیست درخواست ها",
            "REQUEST_DETAILS": "جزئیات درخواست",
            "ADD_NEW_REQUEST_CARDLESS_NEW": "افزودن درخواست جدید",
            "ADD_NEW_REQUEST_CARDLESS_SERVICES": "افزودن درخواست خدمات بدون کارت",
            "CARD_LESS_DETAILS": "جزییات درخواست",

            "NEXT_STAGE": "مرحله بعد",
            "REQUEST_TYPE": "نوع درخواست",
            "WITHDRAWAL": "برداشت وجه",
            "AMOUNT_WITHDRAWAL": "مبلغ قابل برداشت",
            "COMPLETE_CART_INFORMATION": "تکمیل اطلاعات کارت ",
            "TAX_VALUE": "مبلغ کارمزد",
            "EXPIRE_DATE_ASSIGNMENT": "زمان انقضا حواله",
            "CARD_LESS_SERVICES_PASSWORD": "رمز حواله خدمات بدون کارت(4 رقم به دلخواه مشتری)",
            "CARD_LESS_SERVICES_PASSWORD_REPEAT": "تکرار رمز حواله خدمات بدون کارت",
            "CARD_LESS_RECEIPT": "رسید پرداخت بدون کارت",
            "PAY_RECEIPT": "شماره شناسه پرداخت",
            "SEND_RECEIPT": "ارسال رسید",
            "INCORRECT_REPEATED_PASSWORD": "رمز تکرار شده صحیح نیست",
            "CASH_WITHDRAW": "برداشت وجه",
            "REQ_DATE_TIME": "تاریخ ثبت",
            "REQ_AMOUNT": "مبلغ مجاز",
            "REAL_AMOUNT": "مبلغ برداشت شده",
            "REQ_STATUS": "وضعیت درخواست",
            "REVOKE": "منقضی شده",
            // "CANCEL": "لغو",



            "ACTIVE_DYNAMIC_PASS": "فعالسازی رمز پویا",
            "INACTIVE_DYNAMIC_PASS": "غیرفعالسازی رمز پویا",
            "DELETE_DYNAMIC_PASS": "حذف رمز پویا",
            "DEACTIVE_DYNAMIC_PASS": "حذف رمز پویا",
            "DISABLE_DYNAMIC_PASS": "غیرفعالسازی رمز پویا",
            "INQUIRE_DYNAMIC_PASS": "استعلام وضعیت رمز پویا",
            "SUCCESSFUL_ACCOUNT_DEACTIVATE": "درخواست شما با موفقیت انجام شد",
            "CONFIRM_MOBILE_NUMBER": "تایید شماره همراه",
            "CONFIRM_MOBILE_NUMBER_MSG": "لطفا رمز پیامک شده را برای تایید شماره همراه خود وارد نمایید و رمز فعالسازی را دریافت نمایید.",
            "MESSAGE_PASS": "رمز پیامکی",
            "SELECT_NUMBER": "انتخاب شماره همراه",
            "SELECT_NUMBER_OTP_ACTIVATE": "شماره همراه مورد نظر را انتخاب کنید",
            "HARIM_ACTIVATE": "فعالسازی هریم",
            "SERIAL": "سریال",
            "SERIAL_ACTIVATE": "سریال فعالسازی",
            "SERIAL_ACTIVATE_MSG": "سریال فعالسازی در قسمت پایین را همراه با کد فعالساز که از طریق پیامک ارسال شده است را در اپلیکیشن همراز وارد کرده و رمز پویای خود را فعال کنید.",
            "GET_DYNAMIC_PASS_CONFIRM1": "از این پس رمزهای پویای خود را از طریق شماره همراه",
            "GET_DYNAMIC_PASS_CONFIRM2": "دریافت می نمایید",
            "GET_DYNAMIC_PASS_CONFIRM3": "آیا مورد تایید است؟",
            "COME_BACK": "بازگشت",
            "CARD_DISABLE_DYNAMIC_PASS1": "رمزپویا برای کارت به شماره",
            "CARD_DISABLE_DYNAMIC_PASS2": " غیرفعال می گردد.",
            "CARD_DEACTIVE_DYNAMIC_PASS": " حذف می گردد.",
            "CARD_STATUS_DYNAMIC_PASS": "سرویس درخواستی به زودی راه اندازی خواهد شد",
            "CARD_SUCCESSFUL_CARD_DISABLE": "با موفقیت غیرفعال شد",
            "COPY_SERIAL": "سریال در حافظه موقت ذخیره شد",
            "MORE_INFORMATION": "اطلاعات بیشتر",

            "BRANCH_PHONE": "شماره تلفن شماره",
            "BRANCH_CODE": "کد شعبه",
            "GET_USER_LOCATION_FAILD": "کاربر گرامی دریافت موقعیت مکانی شما با خطا مواجه شد",


            "SELECT_OPTION_10": "10",
            "SELECT_OPTION_20": "20",
            "SELECT_OPTION_30": "30",
            "COPY_RIGHTS": "تمامی حقوق این برنامه متعلق به بانک تجارت است.",
            "PWA_VERSION": "1.3.2",
            "VERSION": "نسخه:1.3.2 ",
            "NEW_VERSION": "1.3.2",
            "VERSION_DATE": "تاریخ انتشار:1402/05/31",
            "INVITE_FRIENDS": "معرفی به دوستان",
            "LATEST_VERSION_CHANGES": "تغییرات آخرین نسخه",
            "NEW_VERSION_CHANGES": "تغییرات نسخه",
            "FEATURE1": "- اضافه شدن قابلیت اسکن کد QR روی برگه چک به منظور درج خودکار اطلاعات در فیلدهای مربوطه",
            "FEATURE2": "- امکان ثبت مشخصات اشخاص حقوقی در قسمت ذینفع(گیرنده) چک",
            "FEATURE3": "- امکان اشتراک گذاری رسید عملیات چک های صیادی",
            "FEATURE4": "- بهبود سایر خدمات چک صیادی",
            "FEATURE5": "- بهینه سازی برخی موارد رابط کاربری",

            "COMMENT_SEND": "ارسال نظر",
            "NAME_FAMILY": "نام و نام خانوادگی",
            "MESSAGE_TEXT": "متن پیام",
            "COMMENT_SUBMIT": "نظر شما با موفقیت ثبت شد",

            "CARD_SERVICES": "خدمات کارت",
            "CARD_BLOCKED_SUCCESSFULLY": "کارت شما با موفقیت مسدود شد",




            "PLATE_INFO": "خدمات خودرو",
            "PLATE_INFO_LIST": "لیست خودروهای من",
            "ADD_NEW_PLATE": "افزودن خودرو جدید",
            "REGISTER_NEW_PLATE": "پلاک خودرو جدید را ثبت کنید",
            "ADD_NEW_PLATE_TITLE": "عوارض خودرو و طرح ترافیک",
            "PALTE_NAME": "نام خودرو",
            "VIN_CARD": "شناسه یکتا خودرو(VIN)",
            "PLATE": "پلاک خودرو",
            "INQUIRE": "استعلام",
            "ASSURE_DELETE_PLATE": "آیا از حذف این خودرو اطمینان دارید؟",
            "UPDATE_PLATE": "ویرایش خودرو",
            "INFORMATION_SUBMIT": "اطلاعات با موفقیت ثبت شد",
            "INFORMATION_SUBMIT_ERROR": "ثبت اطلاعات با مشکل روبروست",

            "AIR_POLLUTION_CONTROLLER": "روزهای مجاز باقیمانده در طرح کنترل آلودگی هوا",
            "FREEWAY_TOLL_CONTROLLER": "سرویس عوارض بزرگراهی",
            "ANNUAL_TOLL_CONTROLLER": "عوارض سالیانه خودرو",
            "TRAFFIC_PAY_LIST": "لیست تردد و پرداخت",
            "SPRING": "بهار",
            "SUMMER": "تابستان",
            "AUTUMN": "پاییز",
            "WINTER": "زمستان",
            "TOTAL_PAID_AMOUNT": "جمع کل",
            "AIR_POLLUTION_CONTROLLER_LIST": "لیست تردد طرح کنترل آلودگی هوا",
            "ANNUAL_TOLL_CONTROLLER_LIST": "لیست عوارض سالیانه",
            "FREEWAY_TOLL_CONTROLLER_LIST": "لیست تردد بزرگراهی",
            "FREEWAY_DATE": "تاریخ تردد",
            "PAYMENT": "پرداخت",
            "UNPAID": "پرداخت نشده",
            "AIR_POLLUTION_PAYMENT": "طرح ترافیک خودرو",
            "AIR_POLLUTION_PAY_AMOUNT": "مبلغ قابل پرداخت",
            "FREEWAY_TOLL_NULL": "ترددی برای خودرو مورد نظر یافت نشد.",
            "FAIL_TO_GET_DATA": "گرفتن اطلاعات با مشکل مواجه شد",

            "FROM_DATE_MORE_THAN_TO_DATE": "بازه تاریخ وارد شده معتبر نمی باشد",
            "ENTER_START_DATE": "تاریخ شروع را وارد کنید ",
            "ENTER_END_DATE": "تاریخ پایان را وارد کنید ",


            "REQUEST_MONEY": "درخواست وجه",
            "REQUEST_DATE": "تاریخ درخواست",
            "REQUEST_AMMOUNT": "مبلغ درخواستی",

            "MY_REQUESTS": "درخواست های من",
            "REQUEST_FROM_ME": "درخواست ها از من",
            "REQUEST_OF": "درخواست از ",
            "REQUEST_DELETE": "حذف درخواست",
            "REQUEST_REJECT": "رد درخواست",
            "INDIVIDUAL": "فردی",
            "GROUPI": "گروهی",
            "REQUEST_MONEY_TIME": "مدت زمان اعتبار",
            "REQUEST_GIVES": "گیرندگان درخواست",
            "AD_PERSON_DEFINE": "فرد جدید را برای درخواست وجه اضافه کنید",
            "REQUEST_MONEY_ADD_NEW_PERSON": "افزودن فرد جدید",
            "REQUEST_MONEY_MOBILE_NUMBER": "تلفن همراه",
            "DEFAULT_AMOUNT": "مبلغ پیش فرض",
            "ENTER_PHONENUMBER": "شماره تلفن همراه نامعتبر است",
            "REQUEST": "درخواست",
            "REQUEST_DESCRIPTION": "توضیحات درخواست",
            "VIEWED": "مشاهده شده",
            "REJECTED": "رد شده",
            "REQUESTERS_DETAILS": "جزییات درخواست شونده ها",
            "REQUESTERS_LIST": "لیست درخواست شونده ها",

            "REQUEST_TOTAL_COUNT": "تعداد پرداخت شده / تعداد کل",
            "REQUEST_TOTAL_AMOUNT": "مبلغ پرداخت شده / مبلغ کل",

            "SAVE_LIST": "لیست ذخیره ها",

            "REQUEST_CONFIRM_DELETE": "آیا از حذف درخواست خود اطمینان دارید؟",
            "EXPIRED": "منقضی شده",
            "ACCEPT": "پذیرش",
            "REJECT_MONEY_REQUEST": "رد درخواست",
            "REQUEST_CONFIRM_REJECT": "آیا از رد درخواست خود اطمینان دارید؟",
            "GROUP_NAME": "نام گروه",
            "SELECT_GROUP": "انتخاب گروه",
            "REQUEST_MONEY_ADDED": "درخواست شما باموفقیت ثبت شد",

            "GROUPS_MANAGMENT": "مدیریت گروه ها",
            "GROUPS_LIST": "لیست گروه ها",
            "ADD_NEW_GROUP": "افزودن گروه جدید",
            "ADD_NEW_MEMBER": "افزودن عضو جدید",
            "ADD_NEW_GROUP_TO_LIST": "افزودن گروه جدید به لیست گروه ها",
            "ADD_NEW_MEMBER_TO_LIST": "افزودن عضو جدید به گروه مخاطبین",
            "GROUP_INFORMATION": "اطلاعات گروه",
            "GROUP_MEMBER_INFORMATION": "اطلاعات عضو گروه",
            "GROUP_MEMBER_NAME": "نام",
            "GROUP_MEMBER_FAMILY": "نام خانوادگی",
            "ADD_GROUP_INFORMATION": "اطلاعات گروه ذخیره شد.",

            "REGISTERED": "ثبت شده",
            "TRANSFER_DESCRIPTION": "شرح",


            "TWO_UNDER_LINE": "_ _",
            "THREE_UNDER_LINE": "_ _ _",

            "CONTACTS": "مخاطبین",
            "CONTACTS_NOT_SUPPORTED": "این قسمت در مرورگر شما پشتیبانی نمیشود",
            "TRANSLATE_RECIPE": "رسید انتقال وجه شتابی(کارت به کارت)",
            "ADVERTISEMENT_SHARE_IMG": "عملیات بانکی خود را به همراه بانک تجارت بسپارید، حتی اگر در بانک ما حساب ندارید.",
            "CAPTCHA": "کد امنیتی",
            "CAPTCHA_ERROR": "کد کپچا نادرست است",
            "CAPTCHA_ENTER_USERNAME": "برای دریافت کد کپچا جدید لطفا نام کاربری را وارد نمایید.",
            "TRANSFER_NULL": "انتقال وجه انجام نشده است",
            "BILL_NULL": "قبضی پرداخت نشده است",
            "INTERNET_NULL": "خرید اینترنت انجام نشده است",
            "CHARGE_NULL": "شارژ همراه انجام نشده است",
            "CHARITY_NULL": "نیکوکاری انجام نشده است",


            "Accept": "قبول",
            "HELP_ACCOUNT_MAINPAGE": "در این بخش حسابهای تعریف شده خود را مشاهده می فرمایید. شما با انتخاب هر حساب قادر خواهید بوداز خدمات موجود که شامل موجودی، انتقال وجه، شارژ سیم کارت، پرداخت قبوض، گردش حساب، بسته اینترنت، نیکوکاری و پرداخت سازمانی استه بهره مند گردید. ",
            "HELP_ACCOUNT_TRANSLATE": "",
            "HELP_ACCOUNT_CHARITY": "جهت انجام عملیات نیکوکاری کافی است در قسمت انتخاب موسسه، موسسه مورد نظر خود را برای نیکوکاری انتخاب کنید و مبلغ دلخواه خود را وارد نموده و گزینه ثبت را برگزینید. در مرحله بعد با وارد نمودن رمز همراه بانک عملیات نیکوکاری با موفقیت انجام خواهد شد.",
            "HELP_ACCOUNT_PAYMENT": "از طریق این امکان قادر خواهید بود پرداخت های سازمانی دارای شناسه واریز خود را پرداخت نمایید. بدین منظور با برگزیدن گزینه انتخاب سازمان مربوطه را انتخاب کنید و شناسه واریز و مبلغ مربوطه را وارد نمایید، با انتخاب گزینه ارسال وارد مرحله بعد شده و پس از وارد نمودن رمز همزاه بانک خود با برگزیدن دکمه ارسال، پرداخت شما صورت خواهد گرفت.",

            "ADD_TO_SCREEN_HEADER_START": "با انجام مراحل زیر نسخه وب اپلیکیشن ",
            "ADD_TO_SCREEN_HEADER_END": "را به صفحه اصلی خود اضافه کرده و بدون نیاز به بروزرسانی از خدمات آن استفاده نمایید.",
            "TAP_BUTTON_SHARE": "1. بر روی share کلیک کنید",
            "TAP_BUTTON_ADD_TO_HOME": "2. گزینه Add to Home Screen فعال کنید",
            "TAP_BUTTON_AD": "3. در قسمت بالا روی Ad کلیک کنید",
            "ADD_TO_SCREEN": "Add"
        }
    }, 
    en: {
        translation: {
            "welcome": "welcome",
            "TEJARAT_BANK": "Tejarat Bank",
            "MOBILE_BANK_TEJERAT": "Mobile bank Tejarat",
            "USER_NAME": "",
            "PASSWORD": "",
            "LOGIN": "",
            "FORGOT_PASS": "",
            "SHETAB_LOGIN_LINK": "",
            "WELLCOM_MESSAGE": "",
            "NATIONAL_CODE": "",
            "PHONE_NUMBER": "",
            "SEND": "Send",
            "ACCOUNTS": "",
            "CARDS": "",
            "SERVIECES": "",
            "USER_ACCOUNT": "",
            "BALANCE": "Balance",
            "MONEY_TRANSFER": "MONEY_TRANSFER",
            "MONEY_TRANSFER_MOBILE": "MONEY_TRANSFER_MOBILE",
            "SIM_CARD_CHARGE": "SIM_CARD_CHARGE",
            "PAY_BILLS": "PAY_BILLS",
            "TURNOVER": "TURNOVER",
            "INTERNET_PACKAGE": "INTERNET_PACKAGE",
            "CHARITY": "CHARITY",
            "ORGAN_PAYMENT": "ORGAN_PAYMENT",
            "DETAILS": "DETAILS",
            "DEST_ACCOUNT_NUMBER": "DEST_ACCOUNT_NUMBER",
            "AMOUNT": "AMOUNT",
            "TRANSFER_COMMENTS": "TRANSFER_COMMENTS",
            "SOURCE_COMMENT": "SOURCE_COMMENT",
            "TARGET_COMMENT": "TARGET_COMMENT",
            "DEPOSIT_ID": "DEPOSIT_ID",
            "TEJARAT": "TEJARAT",
            "MOBILE": "MOBILE",
            "PAYA_SATNA": "PAYA_SATNA",
            "HELP": "Help",
            "ERROR": "ERROR",
            "USER_NAME_IS_EMPTY": "USER_NAME_IS_EMPTY",
            "PASSWORD_IS_EMPTY": "PASSWORD_IS_EMPTY",
            "ADD_ACCOUNT_DESC": "",
            "MOBILE_NUMBER": "s",
            "ADD_ACCOUNT": "ADD_ACCOUNT",
            "DEST_MOBILE_NUMBER": "DEST_MOBILE_NUMBER",
            "DEST_SHEBA_NUMBER": "DEST_SHEBA_NUMBER",
            "LOG_NUMBER": "LOG_NUMBER",
            "FILTER": "FILTER",
            "SEND_LOG": "SEND_LOG",
            "VIEW": "VIEW",
            "LOG_NUMBER_LABLE": "LOG_NUMBER_LABLE",
            "FROM_DATE": "FROM_DATE",
            "TO_DATE": "TO_DATA",
            "SELECT_PLACEHOLDER": "SELECT_PLACEHOLDER",
            "EXIT": "EXIT",
            "WILL_YOU_EXIT": "WILL_YOU_EXIT",
            "YES": "Yes",
            "NO": "No",
            "USERNAME_ID": "USERNAME_ID",
            "SETTINGS": "ُSettings",
            "ABOUT_US": "About us",
            "SEND_COMMENT": "Send comment",
            "RIAL": "RIAL",
            "IRR": "RIAL",
            "ACCOUNT_NUMBER": "ACCOUNT_NUMBER",
            "ACCOUNT_BALANCE": "ACCOUNT_BALANCE",
            "ACCOUNT_BALANCE_UPDATED": "ACCOUNT_BALANCE_UPDATED",
            "SELECT_SOURCE_ACCOUNT": "Select source account",
            "SEARCH": "SEARCH",
            "BLOCK_ACCOUNT": "",
            "BLOCK_ACCOUNT_INQUERY": "",
            "INSTANT_MESSAGE": "",
            "COPY_TO_CILPBOARD": "",
            "EDIT_ACCOUNT_TITLE": "",
            "SOCIAL_SHARING": "",
            "ACCOUNT_INFO": "",
            "DONT_SHOW_ACCOUNT": "",
            "SHOW_CARD_OR_ACCOUNT": "SHOW_CARD_OR_ACCOUNT",
            "DEFAULT_TRANSFER_MOBILE": "",
            "SELECT": "Select",
            "DEST_ACCOUNTS": "",
            "MYSELF_ACCOUNTS": "",
            "ADD": "ADD",
            "ACCOUNT": "Account",
            "CARD": "Card",
            "SHEBA": "Sheba",
            "CARD_TITLE": "Card title",
            "CARD_NUMBER": "Card number",
            "SAVE": "Save",
            "ACCOUNT_TITLE": "Account title",
            "SHEBA_TITLE": "Sheba title",
            "SHEBA_NUMBER": "Sheba number",
            "DEST_ACCOUNTS_MANAGEMENT": "",
            "CHEQUE_MANAGEMENT": "",
            "CHEQUE_INQUERY": "",
            "INSTALLMENT_MANAGEMENT": "",
            "TRANSACTIONS_HISTORY": "",
            "BRANCHES_ARROUND": "",
            "CONVERTS": "",
            "DYNAMIC_PASS_SERVICES": "",
            "ADD_CARD": "",
            "CVV2": "CVV2",
            "EXPIRE_DATE": "",
            "MONTH": "Month",
            "YEAR": "Year",
            "CARD_BALANCE": "Card balance",
            "UPDATE": "Update",
            "DEPOSIT": "Deposit",
            "WITHDRAW": "Withdraw",
            "ENTER_DEST_ACCOUNT_NUMBER_NOTI": "",
            "ENTER_AMOUNT": "",
            "DYNAMIC_PASSWORD": "",
            "ENTER_DYNAMIC_PASSWORD": "",
            "GET_BALANCE": "",
            "HAMRAZ": "",
            "HARIM": "",
            "HAMRAZ_MENU": "",
            "HARIM_MENU": "",
            "ENTER_PASS_CORRECTLY": "",
            "YOUR_REQUEST_SENT_SUCCESSFULLY": "",
            "ACCOUNT_INFO_SAVED": "Account saved successfully",
            "IBAN_INFO_SAVED": "",
            "CARD_INFO_SAVED": "",
            "SECURITY": "security",
            "MANAGER": "MANAGER",
            "CHANGE_PASSWORD": "Change password",
            "MOBILE_BANK_CHANGE_PASSWORD": "",
            "CURRENT_PASSWORD": "",
            "NEW_PASSWORD": "",
            "REPEAT_NEW_PASSWORD": "",
            "SAVE_CHANGE_PASSWORD": "Save",
            "CONFIRM_PASS_MISMATCH": "",
            "ENTER_CURRENT_PASS": "",
            "PASSWORD_CHANGED_SUCCESSFULLY": "",
            "NEW_PASS_LENGTH_ERROR": "",
            "TRANSACTION_DETAIL": "",
            "DOCUMENT_DESC": "",
            "DATE_TIME": "",
            "DOCUMENT_NUMBER": "",
            "TEJARAT_AD_MESSAGE": "",
            "SHARE_RECEIPE_IMAGE": "",
            "SHARE_RECEIPE_CONTENT": "",
            "EMAIL": "",
            "TO": "",
            "TRANSACTIONS_SENT_SUCCESSFULLY": "",
            "BLOCK_ACCOUNT_CARD": "",
            "BLOCK_ACCOUNT_SERVICES": "",
            "ENTER_PASSWORD_TO_BLOCK_ACCOUNT": "",
            "MOBILE_BANK_PASS": "",
            "ACCOUNT_NUMBER_COPIED_TO_CLIPBOARD": "",
            "SHEBA_NUMBER_COPIED_TO_CLIPBOARD": "",
            "CARD_NUMBER_COPIED_TO_CLIPBOARD": "",
            "STATUS": "",
            "TITLE": "",
            "ACTIVE": "",
            "INACTIVE": "",
            "ُSAVE_ACCOUNT": "",
            "ACCOUNT_IS_ACTIVE": "",
            "ACCOUNT_IS_INACTIVE": "",
            "CARD_BALANCE_UPDATED": "",
            "CARD_BALANCE_ENABLE_TEJARAT": "",
            "ENTER_CARD_TITLE": "",
            "ENTER_VALID_CARD_NUMBER": "",
            "CORRECT_CVV2_CODE": "",
            "ENTER_VALID_DATE": "",
            "CONFIRM_TRANSFER": "",
            "TRANSACTION_TYPE": "",
            "SOURCE": "",
            "DESTINATION": "",
            "ACCOUNT_OWNER_NAME": "",
            "IBAM_OWNER_NAME": "",
            "ENTER_MOBILE_BANK_PASSWORD": "",
            "TEJARAT_TRANSFER_ACCOUNT_TO_ACCOUNT": "",
            "TEJARAT_TRANSFER_CARD_TO_CARD": "",
            "ENTER_DEST_IBAN_NUMBER_NOTI": "",
            "ُSOURCE_ACCOUNT": "",
            "DEST_ACCOUNT": "",
            "DATE_AND_TIME": "",
            "TRACKING_CODE": "",
            "REFRENCE_NUMBER": "",
            "STATUS_INQUERY": "",
            "TRANSFRED_SUCCESSFULLY": "",
            "BILL_GENERAL": "",
            "HAMRAH_AVAL": "",
            "TWO_ID_BILL": "",
            "PAYMENT_IDENTIFIRE": "",
            "BILL_IDENTIFIRE": "",
            "BARCODE_READER": "",

            "BUY_CHARGE": "",
            "DIRECT_CHARGE": "",
            "MOBILE_OPERATOR": "",
            "CHARGE_TYPE": "",
            "CAHRGE_AMOUNT": "",
            "PIN_CAHRGE": "",
            "AUTO_CHARGE": "",
            "COMMANDS": "",
            "ADD_NEW_COMMAND": "",
            "SELECT_OPERATOR": "",
            "IRAN_CELL": "",
            "RIGH_TELL": "",
            "ENTER_DEST_CARD_NUMBER_NOTI": "",
            "DEST_CARD_NUMBER": "",
            "DEST_CARDS": "",
            "MYSELF_CARDS": "",
            "INTERNET_MOBILE": "",
            "INTERNET_TDE_LTE": "",
            "INTERNET_TAX_AMOUNT": "",
            "PACKAGE": "",
            "INSTITUTE": "",
            "ORGAN": "",
            "BLOCK_CARD": "",
            "DELETE": "",
            "EDIT_CARD": "",
            "ORGANS": "",
            "BANK": "",
            "DEST_IBAN": "",
            "ENTER_CVV2_CODE": "",
            "ENTER_EXPIRE_DATE": "",
            "SOURCE_CARD": "",
            "DEST_CARD": "",
            "CARD_OWNER_NAME": "",
            "SAVE_CARD": "",
            "DOING": "",
            "SELECT_CHARGE_TYPE": "",
            "SELECT_CHARGE_AMOUNT": "",
            "NO_CHARGE_AVAILABLE_FOR_SELECTED_OPERATOR": "",
            "ENTER_TOPUP_PACKAGE": "",
            "ENTER_TOPUP_OPERATOR": "",
            "ENTER_TOPUP_MOBILE": "",
            "DIRECT:": "",
            "OPERATOR_TRACENUMBER": "",
            "CONFIRM_PUR_CHARGE": "",
            "CLICK_CHARGE_CODE_TO_CALL": "",
            "CHARGE_CODE_COPIED_TO_CLIPBOARD": "",
            "CONFIRM_CHARITY_TRANSFER": "",
            "CHARITY_ORG_NAME": "",
            "CHARITY_ORG_ACCOUNT_NUMBER": "",
            "CHARITY_ORG_CARD_NUMBER": "",
            "PAYA_TRANSFER_MESSAGE": "",
            "SATNA_TRANSFER_MESSAGE": "",
            "ORGAN_OWNER_ACCOUNT": "",
            "CONFIRM_PAY_BILL": "",
            "OPERATIONS": "",
            "BILL_TYPE": "",
            "BILL": "",
            "PAY_BILL_ACCOUNT": "",
            "ENTER_INTERNET_PACKAGE": "",
            "CONFIRM_INTERNET_PACK": "",
            "INTERNET_PACK_TYPE": "",
            "PUR_INTERNET_PACK": "",
            "PREPAID_SIM": "",
            "POSTPAID_SIM": "",
            "PAY_BILL_CARD": "",
            "CONFIRM_ORGAN_TRANSFER": "",
            "INSTANT_MESSAGE_STATUS": "",
            "INACTIVE_INSTANT_MESSAGE_EXP": "",
            "ACTIVE_INSTANT_MESSAGE_EXP": "",
            "IM_ACTIVATION_EXP": "",
            "HIDE_ACCOUNT_CONFIRM_MSG": "",
            "HIDE_CARD_CONFIRM_MSG": "",
            "DELETE_CARD_CONFIRM_MSG": "",
            "DELETE_REPORT_MSG": "",
            "DESTINATION_PHONE_NUMBER": "",
            "CARD_CONFIRMATION_TOP_MSG": "",

            "GAS_TITLE": "",
            "WATER_TITLE": "",
            "ELECTRICITY_TITLE": "",
            "MOBILE_TITLE": "",
            "MOBILE_NOW_TITLE": "",
            "TEL_TITLE": "",
            "TEL_NOW_TITLE": "",
            "SUBSCRIPTION_NUMBER": "",
            "TEL_WITH_PRECODE": "",
            "GROUP": "",
            "DESCRIPTION": "",
            "CUSTOMER_BILL": "",
            "USE_TYPE": "",
            "SUBSCRIPE_NUMBER": "",
            "FILE_NUMBER": "",
            "UNIT_COUNT": "",
            "CAPACITY": "",
            "CURRENT_READING_DATE": "",
            "PREVIOUS_READING_DATE": "",
            "CURRENT_CAONTER_DIGIT": "",
            "PREVIOUS_COUNTER_DIGIT": "",
            "STANDARD_CONSUMPTION": "",
            "BILL_TAXES": "",
            "INSURANCE": "",
            "COUNTER_ACTIVITY": "",
            "SERIAL_NUMBER": "",
            "OTHETR_DEBT": "",
            "REMAINING_DEBT": "",
            "REMAINING_AMOUNT_1000": "",
            "DEDUCTION_AMOUNT_1000": "",
            "VILLAGE_GAZ_TAXES": "",
            "ADDRESS_CODE": "",
            "SHOW_DETAILS": "",
            "HIDE_DETAILS": "",
            "FARSI": "",
            "FINGLISH": "",
            "TRANSFER_TEJARAT": "",
            "TRANSFER_IBAN": "",
            "TRANSFER_CARD": "",
            "OK": "",
            "CANCEL": "",
            "INQUERY": "",
            "INQUIRY": "",
            "CONTINUE": "",
            "SUCCESS": "",
            "HELP_TO": "",
            "PUR_CHARGE": "",
            "pasargad": "",
            "tejarat": "",
            "ayandeh": "",
            "MYSELFE": "",
            "TRY_AGAIN": "",
            "RESTCALL_TIMEOUT_MSG": "Request timeout message",
            "Internal Server Error": "Internal Server Error"
        }
    }

}